access_token = '05917dfb-c9ff-4c0d-9e5c-e9a85fbdae0d'
device_id = 'a9fdfede-95cd-4502-ba07-cb816f100f89'
license_key = 'pIe35S90-137cBdV9-R7D290JL'
private_key = '6GW/uaUtfs88GxXnr1riuDw3jrLwcppoeyREEMtcTmA='
