name: warp

on:
  workflow_dispatch:
  
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4  # ✅ 确保 checkout 是最新版本
        - run: |
            wget -O wgcf https://github.com/ViRb3/wgcf/releases/download/v2.2.25/wgcf_2.2.25_freebsd_amd64
            chmod +x wgcf
            wgcf register
            wgcf generate
